development:
  adapter: mysql2
  database: android
  host: 127.0.0.1
  username: android
  password: androidPlank314
  encoding: utf8

production:
  adapter: mysql2
  database: android
  host: 127.0.0.1
  username: android
  password: androidPlank314
  encoding: utf8
